#!/usr/bin/env bash

# if not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

# import colorscheme from 'wal' asynchronously
# &   # run the process in the background.
# ( ) # hide shell job control messages.
# (/usr/bin/cat $HOME/.config/wpg/sequences &)

eval "$(starship init bash)"

# pyenv
# eval "$(pyenv init -)"

shopt -s histappend
shopt -s histverify
shopt -s cmdhist
shopt -s checkwinsize
shopt -s globstar
shopt -s autocd
shopt -s cdspell
shopt -s direxpand

export HISTFILE="$XDG_DATA_HOME"/bash-history
export HISTCONTROL=ignoreboth
export HISTSIZE=
export HISTFILESIZE=
export HISTTIMEFORMAT="%F %T "

# after each command, append to the history file and reread it
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

# disable scroll lock on ctrl+s
stty -ixon

# change prompt
# PS1='\[\033[01;34m\]\W\[\033[00m\]\$ '

# fzf integration
[ -f /usr/share/fzf/completion.bash ] && source /usr/share/fzf/completion.bash
[ -f /usr/share/fzf/key-bindings.bash ] && source /usr/share/fzf/key-bindings.bash

# goto
[ -s "/usr/share/goto/goto.sh" ] && . /usr/share/goto/goto.sh

source "$XDG_CONFIG_HOME/shell/common"
