#!/bin/sh

while read -r file
do
    case "$1" in
        "C-comma")  convert -rotate 270 "$file" "$file" ;;
        "C-period") convert -rotate 90 "$file" "$file" ;;
        "C-slash")  convert -rotate 180 "$file" "$file" ;;
        "C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
        "C-w")      nitrogen --save --set-zoom-fill "$file" ;;
    esac
done
