#!/bin/sh

clock=$(date '+%I')

case "$clock" in
    "00") icon="🕛" ;;
    "01") icon="🕐" ;;
    "02") icon="🕑" ;;
    "03") icon="🕒" ;;
    "04") icon="🕓" ;;
    "05") icon="🕔" ;;
    "06") icon="🕕" ;;
    "07") icon="🕖" ;;
    "08") icon="🕗" ;;
    "09") icon="🕘" ;;
    "10") icon="🕙" ;;
    "11") icon="🕚" ;;
    "12") icon="🕛" ;;
esac

case $BUTTON in
    1) this-month ;;
    2) setsid -f "$TERMINAL" -e calcurse ;;
    3) notify-send "Appointments" "$(calcurse -d3)" ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

date +"$icon %R"
