#!/bin/sh

userresources=$HOME/.config/x11/xresources
userprofile=$HOME/.config/x11/xprofile
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

[ -f /etc/xprofile ] && . /etc/xprofile
[ -f "$userprofile" ] && . "$userprofile"


# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


xset r rate 180 60 &
xset r 66


[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xkeymap" ] && xkbcomp "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xkeymap" "$DISPLAY" >/dev/null 2>&1


exec picom --experimental-backends --xrender-sync-fence >/dev/null 2>&1 &
# exec "${XDG_CONFIG_HOME:-$HOME/.config}/wpg/wp_init.sh" &
exec nitrogen --restore &
exec xsettingsd &
exec sxhkd -m 1 &
exec unclutter &
exec dwmblocks &
exec clipster -d >/dev/null 2>&1 &
exec dwm
