$pdf_previewer = 'start zathura';
$pdf_mode = 5; # 4 -> use lualatex; 5 -> use xelatex
$xelatex = 'xelatex -shell-escape -interaction=nonstopmode';
$lualatex = 'lualatex --shell-escape --interaction=nonstopmode';
$out_dir = 'pdf';
$view = 'pdf';
@default_files = ('main.tex');
