#!/bin/sh

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down
# $./volume.sh mute

# Arbitrary but unique message tag
msgTag="myvolume"

get_volume() {
    amixer -D pulse get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

is_mute() {
    amixer -D pulse get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

send_notification() {
    volume=$(get_volume)
    if [ "$volume" = "0" ]; then
        icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-muted.svg"
        dunstify -a "volume" -u low -h string:x-dunst-stack-tag:$msgTag \
            -h int:value:"$volume" "volume: ${volume}%" -i "$icon_name"
    else
        if [  "$volume" -lt "10" ]; then
            icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-low.svg"
            dunstify -a "volume" -u low -h string:x-dunst-stack-tag:$msgTag \
                -h int:value:"$volume" "volume: ${volume}%" -i "$icon_name"
        else
            if [ "$volume" -lt "30" ]; then
                icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-low.svg"
            else
                if [ "$volume" -lt "70" ]; then
                    icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-medium.svg"
                else
                    icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-high.svg"
                fi
            fi
        fi
    fi
    # Send the notification
    dunstify -a "volume" -u low -h string:x-dunst-stack-tag:$msgTag \
        -h int:value:"$volume" "volume: ${volume}%" -i "$icon_name"

}

case $1 in
    up)
        # Set the volume on (if it was muted)
        amixer -D pulse set Master on > /dev/null
        # Up the volume (+ 5%)
        amixer -D pulse sset Master 5%+ > /dev/null
        send_notification
        ;;
    down)
        amixer -D pulse set Master on > /dev/null
        amixer -D pulse sset Master 5%- > /dev/null
        send_notification
        ;;
    mute)
        # Toggle mute
        amixer -D pulse set Master 1+ toggle > /dev/null
        if is_mute ; then
            volume=0
            icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-muted.svg"
            dunstify -a "volume" -u low -h string:x-dunst-stack-tag:$msgTag \
                -h int:value:"$volume" "volume: ${volume}%" -i "$icon_name"
        else
            send_notification
        fi
        ;;
esac

canberra-gtk-play -f ~/.local/share/audio/oof.ogg -d "changeVolume"
