#!/bin/sh

if [ "$TERM" = "linux" ]; then
    notify-send 'translation' "$(trans -b -j en:ru -show-original n -show-original-phonetics n -show-translation-phonetics n -show-prompt-message n -show-languages n -no-ansi "$@")"
else
    trans en:ru -j "$@"
fi
