#!/bin/sh

selected="$(curl --silent cht.sh/:list | fzf)"
[ -z "$selected" ] && exit 0

printf "query: "
read -r query

query=$(echo "$query" | tr ' ' '+')
url="cht.sh/$selected/$query"

printf "url %s\n" "$url" &
curl "$url" &
while true; do sleep 1; done
